database:
  production:
    host: '127.0.0.1'
    db: 'tweets_test'
    username: 'root'
    password: 'root'
    port: 3306
    charset: 'utf8'
  development:
    host: '127.0.0.1'
    db: 'tweets_test'
    username: 'root'
    password: 'root'
    port: 3306
    charset: 'utf8'
  test:
    host:
    db:
    username:
    password:
    port: 3306
    charset:
